WITH BIG AS ( 
    SELECT 
    YEAR(DIFFERENTIATION_DATE) AS Y, 
    MAX(SIZE_OF_COLONY) AS L
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT 
BIG.Y AS YEAR,
BIG.L - SIZE_OF_COLONY AS YEAR_DEV,
ID
FROM ECOLI_DATA ED
JOIN BIG ON YEAR(ED.DIFFERENTIATION_DATE) = BIG.Y
ORDER BY YEAR, YEAR_DEV