WITH TMP AS (
    SELECT 
    REPLY_ID,
    BOARD_ID,
    WRITER_ID, 
    CONTENTS,
    DATE_FORMAT(CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
    FROM USED_GOODS_REPLY
)

SELECT
TITLE,
UGB.BOARD_ID,
REPLY_ID,
TMP.WRITER_ID AS WRITER_ID,
TMP.CONTENTS AS CONTENTS,
TMP.CREATED_DATE AS CREATED_DATE
FROM USED_GOODS_BOARD UGB
JOIN TMP ON UGB.BOARD_ID = TMP.BOARD_ID
WHERE YEAR(UGB.CREATED_DATE) = 2022 AND MONTH(UGB.CREATED_DATE) = 10
ORDER BY TMP.CREATED_DATE, TITLE