WITH TWONE AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT 
YEAR(OS.SALES_DATE) AS YEAR,
MONTH(OS.SALES_DATE) AS MONTH,
COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT OS.USER_ID)/ (
    SELECT COUNT(*)
    FROM TWONE
), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE OS
WHERE OS.USER_ID IN (
    SELECT TWONE.USER_ID
    FROM TWONE
)
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
ORDER BY YEAR, MONTH