WITH TMP AS (
    SELECT BS.BOOK_ID, B.AUTHOR_ID, category, sum(sales)*price AS sales
    FROM BOOK_SALES BS
    JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
    WHERE YEAR(BS.SALES_DATE) = 2022 AND MONTH(BS.SALES_DATE) = 1
    GROUP BY BS.BOOK_ID
), TMP2 AS (
    SELECT 
    AUTHOR_ID,
    (
        SELECT AUTHOR_NAME
        FROM AUTHOR
        WHERE AUTHOR.AUTHOR_ID = TMP.AUTHOR_ID
    ) AS AUTHOR_NAME,
    CATEGORY, 
    SUM(sales) as TOTAL_SALES
    FROM TMP
    GROUP BY AUTHOR_ID, category
)

SELECT *
FROM TMP2
ORDER BY AUTHOR_ID, CATEGORY DESC