WITH TMP AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
),
TMP2 AS (
    SELECT FLAVOR, 
       TOTAL_ORDER
    FROM FIRST_HALF
    UNION
    SELECT FLAVOR, 
           TOTAL_ORDER
    FROM TMP
)

SELECT FLAVOR
FROM TMP2
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3