WITH TMP AS (
    SELECT
    MEMBER.MEMBER_ID
    FROM
    (
        SELECT
        MEMBER_ID,
        COUNT(*),
        RANK() over(order by count(*) DESC) as "RANK"
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) AS MEMBER
    WHERE MEMBER.RANK = 1
    LIMIT 1
), TMP2 AS (
    SELECT MEMBER_NAME, MEMBER_ID
    FROM MEMBER_PROFILE
    WHERE MEMBER_ID = (SELECT * FROM TMP)
)

SELECT
TMP2.MEMBER_NAME,
REST_REVIEW.REVIEW_TEXT,
DATE_FORMAT(REST_REVIEW.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW, TMP2
WHERE TMP2.MEMBER_ID = REST_REVIEW.MEMBER_ID
ORDER BY REVIEW_DATE, REST_REVIEW.REVIEW_TEXT
