WITH TMP AS (
    SELECT 
    PARENT_ID AS ID, 
    COUNT(*) AS CNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)

SELECT 
E.ID AS ID,
CASE 
    WHEN CNT IS NULL THEN 0
    ELSE CNT
END AS CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN TMP T ON E.ID = T.ID