#EMP_NO -> HR_EMPLOYEES / HR_GRADE
#EMP_NAME -> HR_EMPLOYEES
#GRADE <- SCORE -> HR_GRADE
#BONUS <- SAL -> HR_EMPLOYEES

SELECT
HE.EMP_NO,
HE.EMP_NAME,
CASE 
    WHEN AVG(SCORE) >= 96 THEN 'S'
    WHEN AVG(SCORE) >= 90 THEN 'A'
    WHEN AVG(SCORE) >= 80 THEN 'B'
    ELSE 'C'
END AS GRADE,
CASE 
    WHEN AVG(SCORE) >= 96 THEN SAL*20/100
    WHEN AVG(SCORE) >= 90 THEN SAL*15/100
    WHEN AVG(SCORE) >= 80 THEN SAL*10/100
    ELSE 0
END AS BONUS
FROM HR_EMPLOYEES HE, HR_GRADE HG
WHERE HE.EMP_NO = HG.EMP_NO
GROUP BY HE.EMP_NO
ORDER BY HE.EMP_NO