WITH RECURSIVE TMP AS (
    SELECT 
    ID,
    1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL
    
    SELECT 
    E.ID,
    TMP.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN TMP ON E.PARENT_ID = TMP.ID
)

SELECT 
COUNT(*) AS COUNT,
GENERATION
FROM TMP
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION