# 월별 미세먼지 - AIR_POLLUTION
# 수원 지역, 연도 별 평균 [ 미세먼지 오염도 | 초미세 먼지 오염도 ]
# PM10, PM2.5, ROUND()
# 연도 오름차순

WITH TMP AS (
    SELECT * FROM AIR_POLLUTION WHERE LOCATION2 = "수원"
)

SELECT YEAR(YM) AS YEAR, ROUND(AVG(PM_VAL1), 2) AS "PM10", ROUND(AVG(PM_VAL2), 2) AS "PM2.5" FROM TMP GROUP BY YEAR(YM) ORDER BY YEAR(YM)
