SELECT 
AI.ANIMAL_ID AS ANIMAL_ID,
AI.NAME AS NAME
FROM ANIMAL_INS AI
LEFT JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.DATETIME IS NOT NULL
ORDER BY DATEDIFF(AO.DATETIME, AI.DATETIME) DESC
LIMIT 2