# 평균 대여 기간 7일 이상인 자동차
# ID, AVERAGE_DURATION
# AVERAGE_DURATION ROUND(1)
# AVERAGE_DURATION DESC, ID DESC
WITH TMP AS (
    SELECT
    CAR_ID,
    ROUND(AVG(DATEDIFF(end_date, start_date)), 1)+1 AS AVERAGE_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
)

SELECT * FROM TMP WHERE AVERAGE_DURATION >= 7
