# 대여 시작일이 2022년 9월에 속하는
# 30일 이상 = 장기 대여
# 대여 기록 ID [ DESC ]
# 데이트 포맷

SELECT
HISTORY_ID AS HISTORY_ID,
CAR_ID AS CAR_ID,
DATE_FORMAT(START_DATE, "%Y-%m-%d") AS START_DATE,
DATE_FORMAT(END_DATE, "%Y-%m-%d") AS END_DATE,
CASE
WHEN DATEDIFF(END_DATE, START_DATE) >= 29 THEN "장기 대여"
ELSE "단기 대여"
END AS "RENT_TYPE"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) = 9
ORDER BY HISTORY_ID DESC
