# USED_GOODS_BOARD
# USED_GOODS_FILE
# 조회수가 가장 높은 중고거래 게시물의 첨부 파일 경로
# 파일 아이디 내림차순
# /home/grep/src/BOARD_ID/FILE_ID+FILE_NAME+FILE_EXT


SELECT
CONCAT("/home/grep/src/", B.BOARD_ID, "/", F.FILE_ID, F.FILE_NAME, F.FILE_EXT) as FILE_PATH
FROM USED_GOODS_BOARD B, USED_GOODS_FILE F
WHERE B.VIEWS = ( SELECT MAX(VIEWS) FROM USED_GOODS_BOARD ) AND B.BOARD_ID = F.BOARD_ID
ORDER BY F.FILE_ID DESC
