SELECT 
A.APNT_NO AS APNT_NO,
P.PT_NAME AS PT_NAME,
P.PT_NO AS PT_NO,
A.MCDP_CD AS MCDP_CD,
D.DR_NAME AS DR_NAME,
A.APNT_YMD AS APNT_YMD
FROM APPOINTMENT A
JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
JOIN PATIENT P ON A.PT_NO = P.PT_NO
WHERE D.MCDP_CD = "CS" AND A.APNT_CNCL_YN = "N" AND DATE_FORMAT(A.APNT_YMD, "%Y-%m-%d") = DATE_FORMAT("2022-04-13","%Y-%m-%d")
ORDER BY APNT_YMD
